[package]
name = "virtual-block-device-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
prometheus = "0.14.0"
tokio = { version = "1.45.1", features = ["full"] }
warp = "0.3.7"
